### ISSUE TITLE
parafac: Add support for missing values

### ISSUE THREAD

**Issue by slang03** [waikato-datamining/multiway-algorithms#1]
PARAFAC support for missing values can be added quite easily as follows:

In each iteration a missing value x_ijk can be estimated by  x_ijk = sum_{1..F} (a_if * b_jf * c_kf)

The easiest approach would be to store a mask in the beginning that indicates which indices ijk had missing values and update the X tensor after each iteration with the reconstructed values from A,B,C. The reconstruction is calculated in each iteration anyway to compute the loss so this only needs to be cached and used for value estimation in a second step.

**Comment by fracpete** [comment]
How to code missing values? Double.NaN?

**Comment by slang03** [comment]
Yes, that's how I did it. See also e.g.:
https://github.com/waikato-datamining/multiway-algorithms/blob/b67699f10ac34550a45e4f82130b57370d08b8d1/src/main/java/nz/ac/waikato/cms/adams/multiway/data/DataReader.java#L81

Should be sufficient for now.

**Comment by slang03** [comment]
Moved to [General Enhancements](https://github.com/waikato-datamining/multiway-algorithms/issues/2).
