### ISSUE TITLE
Why Tensor?

### ISSUE THREAD

**Issue by AndreGuerra123** [waikato-datamining/multiway-algorithms#4]
Hello, I really appreciated this library although I know it is just very young. 
I think I will greatly benefit of such platform written in Java. I have real-time data in multidimensional data running in simulators which I use for testing, but in our lab great deal of the data acquired is multidimensional.
Currently, the biggest issue I see in the application of multiway algorithms is that they usually are not easily generalised for multiway (>3 modes) datasets. I've done a small literature review and I always find reports of incredible improvements (very "occult" benchmarks). These decomposition algorithms are rarely open source (TensorPy being an exception) and I think the major improvements have resulted almost exclusively of distributed vectorization in MPPs. I have collected a list of these algorithms (unfortunately not all the code) and I really want to contribute to this project. 
My main question over this specific implementation is related to the interface Tensor. Why is it needed? Why cannot one just use the FeatureVectors (INDArrays) of a DataSet (nd4j, I saw that you contribute to both projects)? If I'm not mistaken you use it to obtain data in other modality but shouldn't these algorithms work independently of the modality?
Best regards, 
Andre

**Comment by slang03** [comment]
Hi Andre,

our main idea with the `Tensor` object was to make the library independent from its underlying implementation (which is Nd4j at the moment). So users could dynamically switch between a tensor-nd4j or e.g. a tensor-apache-commons backend without much hassle and change in the actual algorithm code. A first implementation of the separation can be found in the [tensor-impl-extraction](https://github.com/waikato-datamining/multiway-algorithms/tree/tensor-impl-extraction) branch. But due to the fact, that Nd4j is currently basically the only library that supports all necessary tensor operations we stick with Nd4j.

**Comment by slang03** [comment]
> How could we store multiple samples of ND4J tensors without increasing the modality? Probably algorithms should train on a specific dataset like iterator.

I'm not sure if I get you right here, could you please provide an example what you mean? What do you mean by `modality`?

**Comment by AndreGuerra123** [comment]
So, double[][][] has a rank or modality of 3. Inside each mode could be different dimensionalities. As a practical example, Let's say a spectroscopic sample double[][], the modes would be Absorbance and Wavelength. The mode Wavelength could have a dimensionality of 4000, like 220nm,221nm,222nm,...4220nm. I recently asked in DL4J how they store tensors/array and they refered to the Nd4j.pile() however that increases the modality. Is there a better solution?

**Comment by slang03** [comment]
I don't think you can stack tensors of different dimensions with the same order without increasing the modality/order in an easy way. You could merge them on a certain mode by concatenation or something but you would loose spatial information throughout the modes. Apart from that, multiway algorithms usually expect the input to be of a fixed dimension (i_1, ..., i_n).
