### ISSUE TITLE
Allow external process to stop build process

### ISSUE THREAD

**Issue by fracpete** [waikato-datamining/multiway-algorithms#5]
* iterative algorithms like PARAFAC can take a long time to finish
* introduce a `stopExecution()` (or similar method) that allows an external process to stop the build and/or filter process in a controlled fashion

**Comment by slang03** [comment]
Added in b9d931fa601ebaceb28443039adb83a9bf115a01 and b3f14d57c969dc86900bff0c53b28cf967201ed5.
